# Generated by Django 2.1.4 on 2018-12-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
                ('date', models.DateTimeField(verbose_name='tweet date: ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('activate', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='twitter.User'),
        ),
    ]
